/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CategoryType = "Battery Tray" | "Four-Wheeler Batteries" | "Inverter Trolley" | "Inverters" | "Others" | "Solar PCU" | "Two-Wheeler Batteries" | "UPS Battery";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "delivered" | "pending" | "processing" | "shipped";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OrderItems {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  order_id: number | null;
  product_id: number | null;
  product_title: string;
  quantity: number;
  total_price: Numeric;
  unit_price: Numeric;
}

export interface Orders {
  billing_address: Json | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  notes: string | null;
  payment_method: string | null;
  payment_status: Generated<string | null>;
  shipping_address: Json;
  status: Generated<OrderStatus | null>;
  total_amount: Numeric;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface Products {
  brand: string;
  category: CategoryType;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  dp_price: Numeric;
  id: Generated<number>;
  image_url: string | null;
  is_active: Generated<boolean | null>;
  mrp_price: Numeric;
  specifications: Json | null;
  stock: Generated<number | null>;
  tags: string[] | null;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Sessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: string;
  last_accessed: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface UserAnalytics {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  last_order_date: Timestamp | null;
  orders_cancelled: Generated<number | null>;
  orders_completed: Generated<number | null>;
  orders_pending: Generated<number | null>;
  total_orders: Generated<number | null>;
  total_spent: Generated<Numeric | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface UserPasswords {
  created_at: Generated<Timestamp | null>;
  password_hash: string;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp | null>;
  display_name: string;
  email: string;
  id: Generated<number>;
  role: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface UserWishlists {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  product_id: number;
  user_id: number;
}

export interface DB {
  order_items: OrderItems;
  orders: Orders;
  products: Products;
  sessions: Sessions;
  user_analytics: UserAnalytics;
  user_passwords: UserPasswords;
  user_wishlists: UserWishlists;
  users: Users;
}
